name: jewelcraft_ai
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Utilidades
  flutter_dotenv: ^5.1.0   # ← una sola vez y bien indentado

  # Core UI y responsive
  sizer: ^2.0.15
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  web: ^1.1.1

  # Funcionalidades
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0
  model_viewer_plus: ^1.9.3
  record: ^6.0.0
  permission_handler: ^11.1.0
  audio_waveforms: ^1.3.0
  path_provider: ^2.1.2
  lottie: ^2.7.0
  universal_html: ^2.2.4
  flutter_drawing_board: ^0.9.8
  image_picker: ^1.0.4
  file_picker: ^8.1.7
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
