name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: stable

      - name: Instalar dependencias
        run: flutter pub get

      - name: Crear archivo .env con las claves secretas
        run: |
          echo "ALLTICK_API_KEY=${{ secrets.ALLTICK_API_KEY }}" > .env
          echo "REPLICATE_API_TOKEN=${{ secrets.REPLICATE_API_TOKEN }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env    
          echo "TRIPO3D_API_KEY=${{ secrets.TRIPO3D_API_KEY }}" >> .env
      - name: Construir APK
        run: flutter build apk --release

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
